name: Flask App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      user: postgres
      password: postgres
      host: localhost
      port: 5432
      dbname: test_db
      FLASK_ENV: development
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/requirements.txt
          
      - name: Run tests
        run: |
          python -m pytest Backend || echo "No tests defined yet"
        continue-on-error: true
        
      - name: Test Flask app
        run: |
          export FLASK_APP=Backend/app.py
          python -m flask run --host=0.0.0.0 --port=5000 &
          sleep 10
          curl http://localhost:5000
        env:
          user: postgres
          password: postgres
          host: localhost
          port: 5432
          dbname: test_db
          FLASK_ENV: development
